### ISSUE TITLE
stripping of unneeded operators may not work sufficiently

### ISSUE THREAD

**Issue by niftg** [uakci/toadua#1]
It seems that in the method `parse_query()` of `./static/frontend.js`, stripping unneeded conjunctive operators doesn't work sufficiently in some cases (ex. the query `kani|koni !@examples`, the output of which contains the array `["or",["not",["user","examples"]]]]`).
In [my branch `behead`](https://github.com/niftg/toadua/tree/behead), I tried to treat such cases with a recursive function. Please take a look.

**Comment by uakci** [comment]
Indeed this is an issue. In fact, I've been aware of it ever since I wrote the code, but I didn't have the time to fix.

One simple fix would be to strip from the inside towards the outside, so that unneeded 'or's are stripped at the 'or' level, before the 'and's are stripped at the 'and' level.

Your solution is good, but it uses modern JavaScript, and the frontend code is the only part of the codebase I've kept ES5-compatible.

I'll write a fix of mine soon if you don't mind. Thanks for the report and reminder!
