### ISSUE TITLE
Update Toaq text entry helpers for Delta

### ISSUE THREAD

**Issue by lynn** [uakci/toadua#23]
When adding a new lemma, or typing inside `**nuımlaı**`…
* `-` should become a prefix underdot on the last vowel.
* `vy?|wy?|w` should become ꝡ.
* `ka4` should be converted to `kâ`, not `kả`.

**Comment by uakci** [comment]
Yeah, this is something we should be able to do. For anybody wondering, the relevant code is placed [here in the awkwardly stranded `frontend/shared` directory](https://github.com/uakci/toadua/blob/55babb6acb50ec06e823c4aa9a5522e59cfc6872/frontend/shared/index.ts#L17-L59).

**Comment by lynn** [comment]
Thought: Normalizing `bu-` to bu-underdot too universally will prevent us from entering and searching for dictionary forms of prefixes, which I believe do want the hyphen. (I thiiink a regex like `-(?=\w)` is right.)

**Comment by uakci** [comment]
I wouldn't mind **bụ** becoming the actual dictionary spelling (and since the database normalizes itself on startup, this change would not require users to edit their entries). But otherwise yeah, plus that makes some sense anyway since you cannot convert a hyphen the moment you see it (because then there'd be no way of knowing if a following vowel should be padded with an apostrophe, as in **háo-ao** → **hạ́o'ao**).

**Comment by uakci** [comment]
Note that the only replacement implemented for ⟨ꝡ⟩ **in the search field** (but not during composition) is ⟨vy⟩. Anything more complex than this would've required overhauling some part of the search logic (I don't really even want to begin to wonder which ones it would be), something that is out-of-budget for the time being. If this turns out to be a big usability issue then please reopen #21.
